/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace CollateralizedFacility {
      
    export type FacilityStruct = {borrower: AddressLike, state: BigNumberish, lockedCash: BigNumberish, titleTokenId: BigNumberish, tradeFinanceRefId: BigNumberish}

    export type FacilityStructOutput = [borrower: string, state: bigint, lockedCash: bigint, titleTokenId: bigint, tradeFinanceRefId: bigint] & {borrower: string, state: bigint, lockedCash: bigint, titleTokenId: bigint, tradeFinanceRefId: bigint }
  
    }

  export interface CollateralizedFacilityInterface extends Interface {
    getFunction(nameOrSignature: "COMPLIANCE_ROLE" | "DEFAULT_ADMIN_ROLE" | "FACILITY_BANKER_ROLE" | "LIQUIDATION_AGENT_ROLE" | "applyComplianceHold" | "cashToken" | "commenceLiquidation" | "createFacility" | "finalizeLiquidation" | "fundAndEncumber" | "getFacility" | "getFacilityParts" | "getRoleAdmin" | "grantRole" | "hasRole" | "nextFacilityId" | "onERC721Received" | "releaseComplianceHold" | "releaseFacility" | "renounceRole" | "revokeRole" | "supportsInterface" | "titleToken"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ComplianceHoldApplied" | "ComplianceHoldReleased" | "FacilityCreated" | "FacilityFunded" | "FacilityReleasedNormally" | "LiquidationCommenced" | "LiquidationFinalized" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'COMPLIANCE_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'FACILITY_BANKER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'LIQUIDATION_AGENT_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'applyComplianceHold', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cashToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'commenceLiquidation', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createFacility', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'finalizeLiquidation', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'fundAndEncumber', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getFacility', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getFacilityParts', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'nextFacilityId', values?: undefined): string;
encodeFunctionData(functionFragment: 'onERC721Received', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'releaseComplianceHold', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'releaseFacility', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'titleToken', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'COMPLIANCE_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FACILITY_BANKER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'LIQUIDATION_AGENT_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'applyComplianceHold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cashToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commenceLiquidation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createFacility', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeLiquidation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundAndEncumber', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFacility', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFacilityParts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextFacilityId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC721Received', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseComplianceHold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseFacility', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'titleToken', data: BytesLike): Result;
  }

  
    export namespace ComplianceHoldAppliedEvent {
      export type InputTuple = [facilityId: BigNumberish, actor: AddressLike];
      export type OutputTuple = [facilityId: bigint, actor: string];
      export interface OutputObject {facilityId: bigint, actor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ComplianceHoldReleasedEvent {
      export type InputTuple = [facilityId: BigNumberish, actor: AddressLike];
      export type OutputTuple = [facilityId: bigint, actor: string];
      export interface OutputObject {facilityId: bigint, actor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FacilityCreatedEvent {
      export type InputTuple = [facilityId: BigNumberish, borrower: AddressLike, tradeFinanceRefId: BigNumberish];
      export type OutputTuple = [facilityId: bigint, borrower: string, tradeFinanceRefId: bigint];
      export interface OutputObject {facilityId: bigint, borrower: string, tradeFinanceRefId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FacilityFundedEvent {
      export type InputTuple = [facilityId: BigNumberish, borrower: AddressLike, cashAmount: BigNumberish, titleTokenId: BigNumberish];
      export type OutputTuple = [facilityId: bigint, borrower: string, cashAmount: bigint, titleTokenId: bigint];
      export interface OutputObject {facilityId: bigint, borrower: string, cashAmount: bigint, titleTokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FacilityReleasedNormallyEvent {
      export type InputTuple = [facilityId: BigNumberish, borrower: AddressLike];
      export type OutputTuple = [facilityId: bigint, borrower: string];
      export interface OutputObject {facilityId: bigint, borrower: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LiquidationCommencedEvent {
      export type InputTuple = [facilityId: BigNumberish, actor: AddressLike];
      export type OutputTuple = [facilityId: bigint, actor: string];
      export interface OutputObject {facilityId: bigint, actor: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LiquidationFinalizedEvent {
      export type InputTuple = [facilityId: BigNumberish, recovery: AddressLike, cashTransferred: BigNumberish, titleTokenIdTransferred: BigNumberish];
      export type OutputTuple = [facilityId: bigint, recovery: string, cashTransferred: bigint, titleTokenIdTransferred: bigint];
      export interface OutputObject {facilityId: bigint, recovery: string, cashTransferred: bigint, titleTokenIdTransferred: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CollateralizedFacility extends BaseContract {
    
    connect(runner?: ContractRunner | null): CollateralizedFacility;
    waitForDeployment(): Promise<this>;

    interface: CollateralizedFacilityInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    COMPLIANCE_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    FACILITY_BANKER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    LIQUIDATION_AGENT_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    applyComplianceHold: TypedContractMethod<
      [facilityId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cashToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    commenceLiquidation: TypedContractMethod<
      [facilityId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createFacility: TypedContractMethod<
      [borrower: AddressLike, tradeFinanceRefId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    finalizeLiquidation: TypedContractMethod<
      [facilityId: BigNumberish, recovery: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    fundAndEncumber: TypedContractMethod<
      [facilityId: BigNumberish, cashAmount: BigNumberish, titleTokenId_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getFacility: TypedContractMethod<
      [facilityId: BigNumberish, ],
      [CollateralizedFacility.FacilityStructOutput],
      'view'
    >
    

    
    getFacilityParts: TypedContractMethod<
      [facilityId: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint] & {borrower: string, state: bigint, lockedCash: bigint, titleTokenId: bigint, tradeFinanceRefId: bigint }],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    nextFacilityId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    onERC721Received: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    releaseComplianceHold: TypedContractMethod<
      [facilityId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    releaseFacility: TypedContractMethod<
      [facilityId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    titleToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'COMPLIANCE_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'FACILITY_BANKER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'LIQUIDATION_AGENT_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'applyComplianceHold'): TypedContractMethod<
      [facilityId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cashToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'commenceLiquidation'): TypedContractMethod<
      [facilityId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createFacility'): TypedContractMethod<
      [borrower: AddressLike, tradeFinanceRefId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalizeLiquidation'): TypedContractMethod<
      [facilityId: BigNumberish, recovery: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundAndEncumber'): TypedContractMethod<
      [facilityId: BigNumberish, cashAmount: BigNumberish, titleTokenId_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getFacility'): TypedContractMethod<
      [facilityId: BigNumberish, ],
      [CollateralizedFacility.FacilityStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getFacilityParts'): TypedContractMethod<
      [facilityId: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint] & {borrower: string, state: bigint, lockedCash: bigint, titleTokenId: bigint, tradeFinanceRefId: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'nextFacilityId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'onERC721Received'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseComplianceHold'): TypedContractMethod<
      [facilityId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseFacility'): TypedContractMethod<
      [facilityId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'titleToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'ComplianceHoldApplied'): TypedContractEvent<ComplianceHoldAppliedEvent.InputTuple, ComplianceHoldAppliedEvent.OutputTuple, ComplianceHoldAppliedEvent.OutputObject>;
getEvent(key: 'ComplianceHoldReleased'): TypedContractEvent<ComplianceHoldReleasedEvent.InputTuple, ComplianceHoldReleasedEvent.OutputTuple, ComplianceHoldReleasedEvent.OutputObject>;
getEvent(key: 'FacilityCreated'): TypedContractEvent<FacilityCreatedEvent.InputTuple, FacilityCreatedEvent.OutputTuple, FacilityCreatedEvent.OutputObject>;
getEvent(key: 'FacilityFunded'): TypedContractEvent<FacilityFundedEvent.InputTuple, FacilityFundedEvent.OutputTuple, FacilityFundedEvent.OutputObject>;
getEvent(key: 'FacilityReleasedNormally'): TypedContractEvent<FacilityReleasedNormallyEvent.InputTuple, FacilityReleasedNormallyEvent.OutputTuple, FacilityReleasedNormallyEvent.OutputObject>;
getEvent(key: 'LiquidationCommenced'): TypedContractEvent<LiquidationCommencedEvent.InputTuple, LiquidationCommencedEvent.OutputTuple, LiquidationCommencedEvent.OutputObject>;
getEvent(key: 'LiquidationFinalized'): TypedContractEvent<LiquidationFinalizedEvent.InputTuple, LiquidationFinalizedEvent.OutputTuple, LiquidationFinalizedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;

    filters: {
      
      'ComplianceHoldApplied(uint256,address)': TypedContractEvent<ComplianceHoldAppliedEvent.InputTuple, ComplianceHoldAppliedEvent.OutputTuple, ComplianceHoldAppliedEvent.OutputObject>;
      ComplianceHoldApplied: TypedContractEvent<ComplianceHoldAppliedEvent.InputTuple, ComplianceHoldAppliedEvent.OutputTuple, ComplianceHoldAppliedEvent.OutputObject>;
    

      'ComplianceHoldReleased(uint256,address)': TypedContractEvent<ComplianceHoldReleasedEvent.InputTuple, ComplianceHoldReleasedEvent.OutputTuple, ComplianceHoldReleasedEvent.OutputObject>;
      ComplianceHoldReleased: TypedContractEvent<ComplianceHoldReleasedEvent.InputTuple, ComplianceHoldReleasedEvent.OutputTuple, ComplianceHoldReleasedEvent.OutputObject>;
    

      'FacilityCreated(uint256,address,uint256)': TypedContractEvent<FacilityCreatedEvent.InputTuple, FacilityCreatedEvent.OutputTuple, FacilityCreatedEvent.OutputObject>;
      FacilityCreated: TypedContractEvent<FacilityCreatedEvent.InputTuple, FacilityCreatedEvent.OutputTuple, FacilityCreatedEvent.OutputObject>;
    

      'FacilityFunded(uint256,address,uint256,uint256)': TypedContractEvent<FacilityFundedEvent.InputTuple, FacilityFundedEvent.OutputTuple, FacilityFundedEvent.OutputObject>;
      FacilityFunded: TypedContractEvent<FacilityFundedEvent.InputTuple, FacilityFundedEvent.OutputTuple, FacilityFundedEvent.OutputObject>;
    

      'FacilityReleasedNormally(uint256,address)': TypedContractEvent<FacilityReleasedNormallyEvent.InputTuple, FacilityReleasedNormallyEvent.OutputTuple, FacilityReleasedNormallyEvent.OutputObject>;
      FacilityReleasedNormally: TypedContractEvent<FacilityReleasedNormallyEvent.InputTuple, FacilityReleasedNormallyEvent.OutputTuple, FacilityReleasedNormallyEvent.OutputObject>;
    

      'LiquidationCommenced(uint256,address)': TypedContractEvent<LiquidationCommencedEvent.InputTuple, LiquidationCommencedEvent.OutputTuple, LiquidationCommencedEvent.OutputObject>;
      LiquidationCommenced: TypedContractEvent<LiquidationCommencedEvent.InputTuple, LiquidationCommencedEvent.OutputTuple, LiquidationCommencedEvent.OutputObject>;
    

      'LiquidationFinalized(uint256,address,uint256,uint256)': TypedContractEvent<LiquidationFinalizedEvent.InputTuple, LiquidationFinalizedEvent.OutputTuple, LiquidationFinalizedEvent.OutputObject>;
      LiquidationFinalized: TypedContractEvent<LiquidationFinalizedEvent.InputTuple, LiquidationFinalizedEvent.OutputTuple, LiquidationFinalizedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    
    };
  }