/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'CollateralizedFacility', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CollateralizedFacility__factory>
getContractFactory(name: 'CorporateTreasury', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CorporateTreasury__factory>
getContractFactory(name: 'TitleTokenization', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TitleTokenization__factory>
getContractFactory(name: 'TradeFinance', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TradeFinance__factory>

  getContractAt(name: 'CollateralizedFacility', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CollateralizedFacility>
getContractAt(name: 'CorporateTreasury', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CorporateTreasury>
getContractAt(name: 'TitleTokenization', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TitleTokenization>
getContractAt(name: 'TradeFinance', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TradeFinance>

  deployContract(name: 'CollateralizedFacility', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CollateralizedFacility>
deployContract(name: 'CorporateTreasury', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CorporateTreasury>
deployContract(name: 'TitleTokenization', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TitleTokenization>
deployContract(name: 'TradeFinance', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TradeFinance>

  deployContract(name: 'CollateralizedFacility', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CollateralizedFacility>
deployContract(name: 'CorporateTreasury', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CorporateTreasury>
deployContract(name: 'TitleTokenization', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TitleTokenization>
deployContract(name: 'TradeFinance', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TradeFinance>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  